# Generated by Django 3.1.4 on 2020-12-25 09:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Title of the ticket')),
                ('description', models.TextField(verbose_name='Description of the ticket')),
                ('status', models.CharField(choices=[('new', 'New'), ('pro', 'In porgress'), ('fin', 'Finished'), ('tes', 'Testing'), ('wfx', 'Wont fix')], default='new', max_length=3, verbose_name='What is the status of the ticket')),
                ('assigned_to', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Who is responsible for the ticket')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
            },
        ),
    ]
